# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
import sys


# Determine the base path for assets
def get_base_path():
    if hasattr(sys, "_MEIPASS"):
        return Path(sys._MEIPASS) / "assets" / "frame0"
    return Path(__file__).parent / "assets" / "frame0"


ASSETS_PATH = get_base_path()


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("600x400")
window.configure(bg="#FFFFFF")


canvas = Canvas(
    window,
    bg="#FFFFFF",
    height=400,
    width=600,
    bd=0,
    highlightthickness=0,
    relief="ridge",
)

canvas.place(x=0, y=0)
canvas.create_rectangle(300.0, 0.0, 600.0, 400.0, fill="#344865", outline="")

canvas.create_text(
    322.0,
    24.0,
    anchor="nw",
    text="Customer Feedback Form",
    fill="#FFFFFF",
    font=("Inter ExtraBold", 20 * -1),
)

canvas.create_text(
    322.0,
    66.0,
    anchor="nw",
    text="Customer Name",
    fill="#FFFFFF",
    font=("Inter Medium", 16 * -1),
)

canvas.create_text(
    322.0,
    137.0,
    anchor="nw",
    text="Email Address",
    fill="#FFFFFF",
    font=("Inter Medium", 16 * -1),
)

canvas.create_text(
    323.0,
    214.0,
    anchor="nw",
    text="Comments",
    fill="#FFFFFF",
    font=("Inter Medium", 16 * -1),
)

entry_image_1 = PhotoImage(file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(442.5, 107.5, image=entry_image_1)
entry_1 = Entry(bd=0, bg="#D9D9D9", fg="#000716", highlightthickness=0)
entry_1.place(x=321.0, y=92.0, width=243.0, height=29.0)

entry_image_2 = PhotoImage(file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(442.5, 178.5, image=entry_image_2)
entry_2 = Entry(bd=0, bg="#D9D9D9", fg="#000716", highlightthickness=0)
entry_2.place(x=321.0, y=163.0, width=243.0, height=29.0)

entry_image_3 = PhotoImage(file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(443.0, 275.5, image=entry_image_3)
entry_3 = Text(bd=0, bg="#D9D9D9", fg="#000716", highlightthickness=0)
entry_3.place(x=322.0, y=240.0, width=242.0, height=69.0)

button_image_1 = PhotoImage(file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat",
)
button_1.place(x=344.0, y=338.0, width=197.0, height=53.0)

button_image_hover_1 = PhotoImage(file=relative_to_assets("button_hover_1.png"))


def button_1_hover(e):
    button_1.config(image=button_image_hover_1)


def button_1_leave(e):
    button_1.config(image=button_image_1)


button_1.bind("<Enter>", button_1_hover)
button_1.bind("<Leave>", button_1_leave)


image_image_1 = PhotoImage(file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(150.0, 200.0, image=image_image_1)
window.resizable(False, False)
window.mainloop()
